"""Asynchronous Python client for the Nature Remo Cloud API."""

from .client import API_BASE_URL, NatureRemoClient
from .exceptions import (
    NatureRemoApiError,
    NatureRemoAuthError,
    NatureRemoConnectionError,
    NatureRemoError,
    NatureRemoRateLimitError,
)
from .models import (
    APPLIANCE_TYPE_AC,
    APPLIANCE_TYPE_FLOOR_HEATER,
    APPLIANCE_TYPE_IR,
    APPLIANCE_TYPE_LIGHT,
    APPLIANCE_TYPE_LIGHT_PROJECTOR,
    APPLIANCE_TYPE_SMART_METER,
    APPLIANCE_TYPE_TV,
    ENERGY_UNIT_MULTIPLIERS,
    EVENT_HUMIDITY,
    EVENT_ILLUMINATION,
    EVENT_MOVEMENT,
    EVENT_TEMPERATURE,
    TV,
    Aircon,
    AirconExtra,
    AirconExtraOption,
    AirconModeRange,
    AirconSettings,
    Appliance,
    ApplianceButton,
    ApplianceModel,
    Device,
    EchonetLiteAppliance,
    EchonetLiteApplianceProperty,
    EchonetLiteProperty,
    FloorHeater,
    Light,
    LightProjector,
    LightProjectorButton,
    LightState,
    RateLimit,
    SensorValue,
    Signal,
    SmartMeter,
    TVState,
    User,
)

__version__ = "0.4.0"

__all__ = [
    "API_BASE_URL",
    "APPLIANCE_TYPE_AC",
    "APPLIANCE_TYPE_FLOOR_HEATER",
    "APPLIANCE_TYPE_IR",
    "APPLIANCE_TYPE_LIGHT",
    "APPLIANCE_TYPE_LIGHT_PROJECTOR",
    "APPLIANCE_TYPE_SMART_METER",
    "APPLIANCE_TYPE_TV",
    "ENERGY_UNIT_MULTIPLIERS",
    "EVENT_HUMIDITY",
    "EVENT_ILLUMINATION",
    "EVENT_MOVEMENT",
    "EVENT_TEMPERATURE",
    "TV",
    "Aircon",
    "AirconExtra",
    "AirconExtraOption",
    "AirconModeRange",
    "AirconSettings",
    "Appliance",
    "ApplianceButton",
    "ApplianceModel",
    "Device",
    "EchonetLiteAppliance",
    "EchonetLiteApplianceProperty",
    "EchonetLiteProperty",
    "FloorHeater",
    "Light",
    "LightProjector",
    "LightProjectorButton",
    "LightState",
    "NatureRemoApiError",
    "NatureRemoAuthError",
    "NatureRemoClient",
    "NatureRemoConnectionError",
    "NatureRemoError",
    "NatureRemoRateLimitError",
    "RateLimit",
    "SensorValue",
    "Signal",
    "SmartMeter",
    "TVState",
    "User",
]
